#!/usr/bin/env python3
"""Extract the supplied workbook without rewriting its exercises or blank cells."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET
from zipfile import ZipFile

ROOT = Path(__file__).resolve().parents[1]
NS = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
SHEET = "J&T2.0 KGS"


def extract(path):
    with ZipFile(path) as archive:
        strings = ["".join(t.text or "" for t in item.findall(".//m:t", NS))
                   for item in ET.fromstring(archive.read("xl/sharedStrings.xml"))]
        rels = {r.attrib["Id"]: r.attrib["Target"]
                for r in ET.fromstring(archive.read("xl/_rels/workbook.xml.rels"))}
        sheets = ET.fromstring(archive.read("xl/workbook.xml")).find("m:sheets", NS)
        sheet = next(s for s in sheets if s.attrib["name"] == SHEET)
        target = rels[sheet.attrib["{http://schemas.openxmlformats.org/officeDocument/2006/relationships}id"]]
        xml = ET.fromstring(archive.read(target.lstrip("/") if target.startswith("/") else "xl/" + target))
        cells = {}
        for cell in xml.findall(".//m:c", NS):
            value = cell.find("m:v", NS)
            if value is None or value.text is None:
                continue
            text = value.text
            if cell.attrib.get("t") == "s":
                text = strings[int(text)]
            elif cell.attrib.get("t") not in ("str", "e"):
                number = float(text)
                text = int(number) if number.is_integer() else number
            entry = {"value": text}
            formula = cell.find("m:f", NS)
            if formula is not None and formula.text:
                entry["formula"] = formula.text
            cells[cell.attrib["r"]] = entry
    return cells


def column(number):
    result = ""
    while number:
        number, remainder = divmod(number - 1, 26)
        result = chr(65 + remainder) + result
    return result


def generate(path):
    cells = extract(path)
    # Day 4 ends at row 105, with reps/sets but no exercise in block 2.
    # Retain those unassigned cells rather than inventing an exercise.
    ranges = [(57, 66), (69, 78), (81, 90), (93, 105)]
    weeks = {}
    for week in range(1, 13):
        start = 4 + (week - 1) * 5
        days = []
        for first, last in ranges:
            rows = []
            for row in range(first, last + 1):
                refs = [f"{column(start + offset)}{row}" for offset in range(4)]
                values = [cells.get(ref, {}).get("value") for ref in refs]
                if not any(value is not None for value in values):
                    continue
                if isinstance(values[0], str) and values[0].startswith("Day "):
                    continue
                tier = cells.get(f"{'C' if week <= 6 else 'AG'}{row}", {}).get("value")
                entry = {"cell": refs[0], "tier": str(tier) if tier is not None else None,
                         "exercise": values[0], "weight": values[1],
                         "reps": values[2], "sets": values[3]}
                formula = cells.get(refs[1], {}).get("formula")
                if formula:
                    match = re.fullmatch(r"MROUND\((\$[A-Z]+\$\d+)\*([A-Z]+\d+),2\.5\)", formula)
                    if not match:
                        raise ValueError(f"Unsupported load formula {refs[1]}: {formula}")
                    entry["load"] = {"tmCell": match[1].replace("$", ""),
                                     "percent": cells[match[2]]["value"],
                                     "formula": formula}
                rows.append(entry)
            days.append(rows)
        weeks[week] = days
    guidance_refs = ["E52", "E53", "AI52", "AI53", "E137", "E138", "E140",
                     "X139", "X140", "X141", "X142", "X143", "E144", "E145", "E146"]
    source = {"file": path.name, "sheet": SHEET,
              "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
              "guidance": {ref: cells[ref]["value"] for ref in guidance_refs}}
    lines = ["// Generated by scripts/import-spreadsheet.py. Do not edit by hand.",
             "export const SPREADSHEET_SOURCE = " + json.dumps(source, ensure_ascii=False, indent=2) + ";",
             "export const SPREADSHEET_WEEKS = {"]
    for week, days in weeks.items():
        lines.append(f"  {week}: [")
        for rows in days:
            lines.append("    [")
            lines.extend("      " + json.dumps(row, ensure_ascii=False) + "," for row in rows)
            lines.append("    ],")
        lines.append("  ],")
    lines.append("};\n")
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--workbook", type=Path, default=ROOT / "source/GZCL-Free-Compendium.xlsx")
    args = parser.parse_args()
    output = ROOT / "js/spreadsheet-data.js"
    content = generate(args.workbook)
    if args.check:
        if output.read_text() != content:
            raise SystemExit("Spreadsheet data differs; regenerate it.")
        print("PASS: all 48 sessions and guidance match the source workbook.")
    else:
        output.write_text(content)
        print(f"Generated {output}")
